#!/usr/bin/env python3
"""
Automated SEO migration helper for static-sites.
Inputs:
- export.json (generated by export step) containing old URLs and slugs
- domain (base for the new canonical URLs)
Outputs:
- redirects.json  (structure: {"redirects": [{"from":, "to":, "status": 301}, ...]})
- redirects_netlify.txt (Netlify-style redirects: "/old-path" "to-path" 301)
- sitemap.xml
- robots.txt
"""
import json
import os
import sys
import argparse
from urllib.parse import urlparse
from datetime import datetime

def iso_date(ts: str) -> str:
    if not ts:
        return ''
    try:
        # Handle ISO 8601 with or without Z
        ts = ts.replace('Z', '+00:00')
        dt = datetime.fromisoformat(ts)
        return dt.date().isoformat()
    except Exception:
        return ''

def main():
    parser = argparse.ArgumentParser(description='SEO migration automation for static sites')
    parser.add_argument('--export-file', default='export.json', help='Path to export.json (default: export.json)')
    parser.add_argument('--domain', default='https://yogakiddy.com', help='Base domain for new URLs (default: https://yogakiddy.com)')
    parser.add_argument('--out-dir', default='seo_migration_output', help='Output directory for generated artifacts')
    parser.add_argument('--html-redirects', action='store_true', help='Generate simple HTML redirect pages for old URLs (GitHub Pages friendly)')
    parser.add_argument('--github-pages', action='store_true', help='Generate GitHub Pages friendly redirects (per-old-path markdown files)')
    args = parser.parse_args()

    export_path = args.export_file
    domain = args.domain.rstrip('/')
    out_dir = args.out_dir
    os.makedirs(out_dir, exist_ok=True)

    with open(export_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    redirects = []
    sitemap_urls = []

    posts = data.get('posts', [])
    for post in posts:
        slug = post.get('slug') or ''
        old_url = post.get('url', '')
        # New canonical URL (trailing slash)
        new_url = f"{domain}/{slug.strip('/')}/" if slug else domain + '/'
        # Build redirect from old to new
        redirects.append({
            'from': old_url,
            'to': new_url,
            'status': 301
        })
        # Sitemap entry
        lastmod = iso_date(post.get('updated_at')) or iso_date(post.get('published_at')) or ''
        sitemap_urls.append({'loc': new_url, 'lastmod': lastmod, 'changefreq': 'monthly', 'priority': '0.8'})

    # Write redirects.json
    with open(os.path.join(out_dir, 'redirects.json'), 'w', encoding='utf-8') as f:
        json.dump({'redirects': redirects}, f, indent=2, ensure_ascii=False)

    # Netlify redirects format
    netlify_lines = []
    for r in redirects:
        # Compute Netlify-from path (strip domain and ensure leading slash)
        raw_from = r['from'] if isinstance(r['from'], str) else str(r['from'])
        path_from = urlparse(raw_from).path
        if not path_from.startswith('/'):
            path_from = '/' + path_from
        # Ensure trailing slash for canonical path
        if not path_from.endswith('/'):
            path_from = path_from + '/'
        # Netlify-to path (new path with trailing slash)
        to_path = (r['to'] if isinstance(r['to'], str) else str(r['to'])).replace(domain, '')
        if not to_path.startswith('/'):
            to_path = '/' + to_path
        if not to_path.endswith('/'):
            to_path = to_path + '/'
        netlify_lines.append(f"{path_from} {to_path} 301")

    with open(os.path.join(out_dir, 'redirects_netlify.txt'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(netlify_lines))

    # HTML redirects for GitHub Pages (static simple redirect pages)
    if args.html_redirects:
        html_out = os.path.join(out_dir, 'redirects_html')
        os.makedirs(html_out, exist_ok=True)
        for r in redirects:
            old_url = r['from']
            new_url = r['to']
            raw_old = old_url if isinstance(old_url, str) else str(old_url)
            old_path = urlparse(raw_old).path
            if old_path.endswith('/'):
                dir_path = old_path
            else:
                dir_path = old_path + '/'
            # Create directory structure mirroring old path
            target_dir = os.path.join(html_out, dir_path.lstrip('/').replace('/', os.sep))
            os.makedirs(target_dir, exist_ok=True)
            html_path = os.path.join(target_dir, 'index.html')
            html_content = f'''<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="refresh" content="0; url={new_url}"><link rel="canonical" href="{new_url}"></head><body>Redirecting to <a href="{new_url}">{new_url}</a></body></html>'''
            with open(html_path, 'w', encoding='utf-8') as hf:
                hf.write(html_content)
        print(f"HTML redirects (GitHub Pages) written to: {html_out}")

    # GitHub Pages redirects (jekyll-redirect-from)
    if args.github_pages:
        gh_out = os.path.join(out_dir, 'gh_pages_redirects')
        os.makedirs(gh_out, exist_ok=True)
        for r in redirects:
            old_url = r['from']
            old_path = urlparse(old_url).path
            if old_path.endswith('/'):
                old_path = old_path[:-1]
            # remove leading slash for directory name
            old_path_rel = old_path.lstrip('/')
            new_path = r['to']
            if new_path.startswith(domain):
                new_path = new_path[len(domain):]
            if not new_path.endswith('/'):
                new_path = new_path + '/'
            gh_dir = os.path.join(gh_out, old_path_rel)
            os.makedirs(gh_dir, exist_ok=True)
            md_path = os.path.join(gh_dir, 'index.md')
            with open(md_path, 'w', encoding='utf-8') as mf:
                mf.write('---\n')
                mf.write('redirect_from:\n')
                mf.write(f'  - {old_path}/\n')
                mf.write(f'  - {old_path}\n')
                mf.write(f'redirect_to: {new_path}\n')
                mf.write('---\n')
        print(f"GitHub Pages redirects created in: {gh_out}")

    # Write sitemap.xml
    sitemap_path = os.path.join(out_dir, 'sitemap.xml')
    with open(sitemap_path, 'w', encoding='utf-8') as f:
        f.write('<?xml version="1.0" encoding="UTF-8"?>\n')
        f.write('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n')
        for item in sitemap_urls:
            f.write('  <url>\n')
            f.write(f'    <loc>{item["loc"]}</loc>\n')
            if item.get('lastmod'):
                f.write(f'    <lastmod>{item["lastmod"]}</lastmod>\n')
            f.write(f'    <changefreq>{item.get("changefreq", "monthly")}</changefreq>\n')
            f.write(f'    <priority>{item.get("priority", "0.8")}</priority>\n')
            f.write('  </url>\n')
        f.write('</urlset>')

    # Write robots.txt
    robots_path = os.path.join(out_dir, 'robots.txt')
    with open(robots_path, 'w', encoding='utf-8') as f:
        f.write('User-agent: *\n')
        f.write('Allow: /assets/\n')
        f.write('Allow: /css/\n')
        f.write('Allow: /js/\n')
        f.write('Disallow: /admin/\n')
        f.write(f'Sitemap: {domain}/sitemap.xml\n')

    print(f"SEO migration artifacts created in: {out_dir}")

if __name__ == '__main__':
    main()
